package com.edu.fatecbt.departamento;
// Generated 20/05/2015 20:15:32 by Hibernate Tools 4.3.1

import com.edu.fatecbt.produto.Produto;
import com.edu.fatecbt.sistema.modelo.ValidatedEntity;
import com.edu.fatecbt.usuario.Usuario;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento", catalog = "trabalho"
)
public class Departamento extends ValidatedEntity implements java.io.Serializable {

    private Integer codDepartamento = 0;
    private Usuario usuario;
    private String descricao;
    private Set<Produto> produtos = new HashSet<Produto>(0);

    public Departamento() {
    }

    public Departamento(Usuario usuario) {
        this.usuario = usuario;
    }

    public Departamento(Usuario usuario, String descricao, Set<Produto> produtos) {
        this.usuario = usuario;
        this.descricao = descricao;
        this.produtos = produtos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "codDepartamento", unique = true, nullable = false)
    public Integer getCodDepartamento() {
        return this.codDepartamento;
    }

    public void setCodDepartamento(Integer codDepartamento) {
        this.codDepartamento = codDepartamento;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario", nullable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name = "descricao", length = 100)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
    public Set<Produto> getProdutos() {
        return this.produtos;
    }

    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }

    @Override
    @Transient
    public boolean isValid() {
        return notEmptyString(descricao) && usuario != null;
    }

}
