package com.edu.fatecbt.saida;
// Generated 20/05/2015 20:15:32 by Hibernate Tools 4.3.1

import com.edu.fatecbt.cliente.Cliente;
import com.edu.fatecbt.produto.Produto;
import com.edu.fatecbt.usuario.Usuario;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Saida generated by hbm2java
 */
@Entity
@Table(name = "saida", catalog = "trabalho"
)
public class Saida implements java.io.Serializable {

    private Integer codSaida = 0;
    private Cliente cliente;
    private Produto produto;
    private Usuario usuario;
    private Date data;
    private Double preco;
    private Double quantidade;
    private Double total;

    public Saida() {
    }

    public Saida(Cliente cliente, Produto produto, Usuario usuario) {
        this.cliente = cliente;
        this.produto = produto;
        this.usuario = usuario;
    }

    public Saida(Cliente cliente, Produto produto, Usuario usuario, Date data, Double preco, Double quantidade, Double total) {
        this.cliente = cliente;
        this.produto = produto;
        this.usuario = usuario;
        this.data = data;
        this.preco = preco;
        this.quantidade = quantidade;
        this.total = total;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "codSaida", unique = true, nullable = false)
    public Integer getCodSaida() {
        return this.codSaida;
    }

    public void setCodSaida(Integer codSaida) {
        this.codSaida = codSaida;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cliente", nullable = false)
    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "produto", nullable = false)
    public Produto getProduto() {
        return this.produto;
    }

    public void setProduto(Produto produto) {
        this.produto = produto;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario", nullable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data", length = 10)
    public Date getData() {
        return this.data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    @Column(name = "preco", precision = 22, scale = 0)
    public Double getPreco() {
        return this.preco;
    }

    public void setPreco(Double preco) {
        this.preco = preco;
    }

    @Column(name = "quantidade", precision = 22, scale = 0)
    public Double getQuantidade() {
        return this.quantidade;
    }

    public void setQuantidade(Double quantidade) {
        this.quantidade = quantidade;
    }

    @Column(name = "total", precision = 22, scale = 0)
    public Double getTotal() {
        return this.total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    @Transient
    public boolean isValid() {
        return cliente != null
                && getProduto() != null
                && getData() != null
                && getPreco() > -1
                && getQuantidade() > 0;
    }

    public void calcularTotal() {
        this.total = quantidade * preco;
    }

}
