package com.edu.fatecbt.fornecedor;
// Generated 20/05/2015 20:15:32 by Hibernate Tools 4.3.1

import com.edu.fatecbt.entrada.Entrada;
import com.edu.fatecbt.sistema.modelo.ValidatedEntity;
import com.edu.fatecbt.usuario.Usuario;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name = "fornecedor", catalog = "trabalho"
)
public class Fornecedor extends ValidatedEntity implements java.io.Serializable {

    private Integer codFornecedor;
    private Usuario usuario;
    private String cnpj;
    private String nome;
    private String endereco;
    private Set<Entrada> entradas = new HashSet<Entrada>(0);

    public Fornecedor() {
    }

    public Fornecedor(Usuario usuario) {
        this.usuario = usuario;
    }

    public Fornecedor(Usuario usuario, String cnpj, String nome, String endereco, Set<Entrada> entradas) {
        this.usuario = usuario;
        this.cnpj = cnpj;
        this.nome = nome;
        this.endereco = endereco;
        this.entradas = entradas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "codFornecedor", unique = true, nullable = false)
    public Integer getCodFornecedor() {
        return this.codFornecedor;
    }

    public void setCodFornecedor(Integer codFornecedor) {
        this.codFornecedor = codFornecedor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario", nullable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name = "cnpj", length = 20)
    public String getCnpj() {
        return this.cnpj;
    }

    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    @Column(name = "nome", length = 80)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "endereco", length = 80)
    public String getEndereco() {
        return this.endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fornecedor")
    public Set<Entrada> getEntradas() {
        return this.entradas;
    }

    public void setEntradas(Set<Entrada> entradas) {
        this.entradas = entradas;
    }

    @Transient
    @Override
    public boolean isValid() {
        return notEmptyString(cnpj, nome, endereco);
//         !cnpj.isEmpty() &&
//         !nome.isEmpty() &&
//         !endereco.isEmpty();
    }

}
