package com.edu.fatecbt.cliente;
// Generated 20/05/2015 20:15:32 by Hibernate Tools 4.3.1

import com.edu.fatecbt.saida.Saida;
import com.edu.fatecbt.sistema.modelo.ValidatedEntity;
import com.edu.fatecbt.usuario.Usuario;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "trabalho"
)
public class Cliente extends ValidatedEntity implements java.io.Serializable {

    private Integer codCliente = 0;
    private Usuario usuario;
    private String cpf;
    private String nome;
    private String endereco;
    private Date dataAniversario;
    private Set<Saida> saidas = new HashSet<Saida>(0);

    public Cliente() {
    }

    public Cliente(Usuario usuario) {
        this.usuario = usuario;
    }

    public Cliente(Usuario usuario, String cpf, String nome, String endereco, Date dataAniversario, Set<Saida> saidas) {
        this.usuario = usuario;
        this.cpf = cpf;
        this.nome = nome;
        this.endereco = endereco;
        this.dataAniversario = dataAniversario;
        this.saidas = saidas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "codCliente", unique = true, nullable = false)
    public Integer getCodCliente() {
        return this.codCliente;
    }

    public void setCodCliente(Integer codCliente) {
        this.codCliente = codCliente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario", nullable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name = "cpf", length = 20)
    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Column(name = "nome", length = 80)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "endereco", length = 80)
    public String getEndereco() {
        return this.endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dataAniversario", length = 10)
    public Date getDataAniversario() {
        return this.dataAniversario;
    }

    public void setDataAniversario(Date dataAniversario) {
        this.dataAniversario = dataAniversario;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
    public Set<Saida> getSaidas() {
        return this.saidas;
    }

    public void setSaidas(Set<Saida> saidas) {
        this.saidas = saidas;
    }

    @Transient
    public boolean isValid() {
        return notEmptyString(cpf, nome, endereco) && usuario != null;
    }

}
